config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'needs' => 'needs#index'
  get 'needs/new' => 'needs#new'
  post 'needs' => 'needs#create'
  put 'needs/:id/take' => 'needs#take'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/need.rb
class Need < ApplicationRecord
  attribute :is_taken, :boolean, default: false
  attribute :datetime_range_start, :datetime, default: DateTime.now
  attribute :datetime_range_end, :datetime, default: DateTime.now.end_of_day
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController

  def index
    @needs = Need.order :created_at
  end

  def new
    @need = Need.new
  end

  def create
    @need = Need.new(params[:need].permit!)
    @need.save!
    redirect_to '/needs'
  end

  def take
    need = Need.find(params[:id])
    need.is_taken = true
    need.save!
    redirect_to '/needs'
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Materialize</title>

  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta content="/" name="turbolinks-root" />
  <meta content="no-preview" name="turbolinks-cache-control" />

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header_1' %>
<%= render 'layouts/side_bar' %>

<% flash.each do |message_type, message| %>
  <%= javascript_tag "Materialize.toast('#{message}', 4000)" %>
<% end %>

<%= render 'layouts/main' %>

<% if current_page?(root_path) %>
  <%= render 'layouts/footer_2' %>
<% else %>
  <style>
    .page-footer { padding-top: 0px; }
  </style>

  <%= render 'layouts/footer_1' %>
<% end %>

</body>
</html>s

app/views/needs/index.html.erb
<div class="jumbotron">
  <a type="button" class="btn btn-lg btn-default" href="><span class="glyphicon glyphicon-flash"></span> Register</a>
  <a type="button" class="btn btn-lg btn-primary" href=""><span class="glyphicon glyphicon-download"></span> Login</a>
  <div class="text-center">
    <div class="container">
      <a href="/" class="lang-logo">
        <img src="<%= asset_path('volundeer.png') %>" height="80" width="80">
      </a>
      <h2>Volundeering</h2>
      <p>Register for opportunities to volunteer that match your interests, availability and location!</p>
    </div>
  </div>
</div>

<div class="container">
  <table class="table table-striped">
    <br>
      <tr>
        <th>Task asked...</th>
        <th>Approximate Duration</th>
        <th>Keywords</th>
        <th>Available</th>
      </tr>
    <tbody>
      <% @needs.each do |need| %>
        <tr class="need">
          <td>
            <div class="description">
              <p><%= need.description %></p>
            </div>
          </td>
          <td class="time">
            <div>
              <p>
                <span class="duration"><%= need.duration %></span> minutes
                between <span class="datetime_range"> <%= need.datetime_range_start %> </span>
                and <span class="datetime_range"><%= need.datetime_range_end %></span>
              </p>
            </div>
          </td>
          <td>
            <div class="categories">
              <p>
                <%= need.categories%>
              </p>
            </div>
          </td>
          <td>
            <div class="taken">
              <%= button_to "Take it!", {action: "take", id: need.id}, method: :put , :disabled => need.is_taken?
              %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/needs/new.html.erb
<div class="jumbotron">
  <a type="button" class="btn btn-lg btn-default" href="><span class="glyphicon glyphicon-flash"></span> Register</a>
  <a type="button" class="btn btn-lg btn-primary" href=""><span class="glyphicon glyphicon-download"></span> Login</a>
  <div class="text-center">
    <div class="container">
      <a href="/" class="lang-logo">
        <img src="<%= asset_path('volundeer.png') %>" height="80" width="80">
      </a>
      <h2>Volundeering</h2>
      <p>How can we help you? Please fill in the form below.</p>
    </div>
  </div>
</div>

<div class="container">
  <br>
    <%= form_for @need,  url: { action: "create" }, :html => {:class => "form-horizontal center"} do |need| %>
      <div class="form-group">
        I need help with...
        <div class="col-md-8">
          <%= need.text_field :description, class: "form-control", :placeholder => "task..." %>
        </div>
      </div>
      <div class="form-group">
        For approximately...
        <div class="col-md-8">
          <%= need.number_field :duration, class: "form-control", :placeholder => "minutes..." %>
        </div>
      </div>

      <div class="form-group">
        Between...
        <div class="col-md-8">
          <%= need.datetime_local_field :datetime_range_start, class: "form-control" %>
        </div>
        <div class="col-md-8">
          <%= need.datetime_local_field :datetime_range_start, class: "form-control" %>
        </div>
        <br />
      </div>

      <%= need.submit "Submit", class: "btn btn-default btn-primary" %>
    <% end %>
</div>

app/views/welcome/index.html.erb
<div class="split left">
  <div class="centered">
    <%= image_tag("raise_hand.png", :alt => "happy woman") %>
    <p>
      <%= link_to "I want to volunteer!", needs_path, class: 'welcome_page_url' %>
    </p>
  </div>
</div>

<div class="split right">
  <div class="centered">
    <%= image_tag("help.png", :alt => "ask help") %>
    <p>
      <%= link_to "I need some help!", { controller:'needs', action:'new' }, class: 'welcome_page_url' %>
    </p>
  </div>
</div>